// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "retorimac",
    "version": "1"
  },
  "paths": {
    "/registros": {
      "post": {
        "summary": "crearRegistro",
        "description": "",
        "operationId": "crearRegistro.post./registros",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "name",
            "type": "string",
            "description": "name",
            "required": true
          },
          {
            "in": "query",
            "name": "height",
            "type": "string",
            "description": "height",
            "required": true
          },
          {
            "in": "query",
            "name": "mass",
            "type": "string",
            "description": "mass",
            "required": true
          },
          {
            "in": "query",
            "name": "gender",
            "type": "string",
            "description": "gender",
            "required": true
          },
          {
            "in": "query",
            "name": "homeworld",
            "type": "string",
            "description": "homeworld",
            "required": true
          },
          {
            "in": "query",
            "name": "vehicles",
            "type": "string",
            "description": "vehicles",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Devuelve los datos de dynamo como datos de la api Swapi",
            "schema": {
              "$ref": "#/definitions/ListarRegistros"
            }
          }
        }
      },
      "get": {
        "summary": "listarRegistro",
        "description": "",
        "operationId": "listarRegistro.get./registros",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "url",
            "type": "string",
            "description": "api swapi",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "ListarRegistros": {
      "properties": {
        "dynamo": {
          "title": "ListarRegistros.dynamo",
          "type": "string"
        },
        "Swapi": {
          "title": "ListarRegistros.Swapi",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "ListarRegistros",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};